name: Deploy Docker on Server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Cloudflared
        uses: AnimMouse/setup-cloudflared@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            set -e
            cd ~/Spiare
            git pull origin master
            docker compose up -d --remove-orphans